### ISSUE TITLE
TypeError: _value_ not set in __new__, unable to create it ; possible python 3.11 incompatibility

### ISSUE THREAD

**Issue by rktcc** [sandflow/ttconv#386]
```
Arch Linux 6.1.28-1-lts
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] on linux
ttconv 1.0.6b1 (pip install --pre ttconv)
```
Any attempt to use tt with python 3.11 seems to cause an error without success. I'm unable to test at the moment if this is infact 3.11 to blame, versus 3.10, as I can't downgrade python on the system this software is used on.

I've tried compiling from git as well with no change; to be expected as the latest commit was back in January 2023 (pre 3.11)

```
$ tt --help
Traceback (most recent call last):
  File "/usr/lib/python3.11/enum.py", line 260, in __set_name__
    enum_member._value_ = enum_class._member_type_(*args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SccCode.__init__() takes 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pyuser/.local/bin/tt", line 5, in <module>
    from ttconv.tt import main
  File "/home/pyuser/.local/lib/python3.11/site-packages/ttconv/tt.py", line 40, in <module>
    import ttconv.scc.reader as scc_reader
  File "/home/pyuser/.local/lib/python3.11/site-packages/ttconv/scc/reader.py", line 35, in <module>
    from ttconv.scc.codes.attribute_codes import SccAttributeCode
  File "/home/pyuser/.local/lib/python3.11/site-packages/ttconv/scc/codes/attribute_codes.py", line 37, in <module>
    class SccAttributeCode(SccCode, Enum):
  File "/usr/lib/python3.11/enum.py", line 557, in __new__
    raise exc
  File "/usr/lib/python3.11/enum.py", line 266, in __set_name__
    raise new_exc
TypeError: _value_ not set in __new__, unable to create it
```

Just reporting this as I did not see it reported yet, my workflow is unaffected overall. Thanks!

**Comment by palemieux** [comment]
Please review https://github.com/sandflow/ttconv/pull/387
