### ISSUE TITLE
Unable to start tt after install

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [sandflow/ttconv#388]
after install TTconv on mac I got:
```bash
▶ tt
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 260, in __set_name__
    enum_member._value_ = enum_class._member_type_(*args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SccCode.__init__() takes 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/tt", line 5, in <module>
    from ttconv.tt import main
  File "/usr/local/lib/python3.11/site-packages/ttconv/tt.py", line 40, in <module>
    import ttconv.scc.reader as scc_reader
  File "/usr/local/lib/python3.11/site-packages/ttconv/scc/reader.py", line 35, in <module>
    from ttconv.scc.codes.attribute_codes import SccAttributeCode
  File "/usr/local/lib/python3.11/site-packages/ttconv/scc/codes/attribute_codes.py", line 37, in <module>
    class SccAttributeCode(SccCode, Enum):
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 557, in __new__
    raise exc
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 266, in __set_name__
    raise new_exc
TypeError: _value_ not set in __new__, unable to create it
```

**Comment by palemieux** [comment]
This might be related to https://github.com/sandflow/ttconv/issues/386

Have you tried installing from source?

**Comment by palemieux** [comment]
Closed by https://github.com/sandflow/ttconv/releases/tag/1.0.6
