### ISSUE TITLE
SCC > SRT error, Domesday LD Capture: AttributeError: 'NoneType' object has no attribute 'append_text'

### ISSUE THREAD

**Issue by rktcc** [sandflow/ttconv#394]
```
ttconv 1.0.7 (pip install --pre ttconv)
python 3.11
```

[head.scc.txt](https://github.com/sandflow/ttconv/files/12340307/head.scc.txt) (rename from .txt to .scc since Github didn't like .scc.)

This is an SCC file extracted from a LaserDisc film captured using a Domesday Duplicator. Additionally, this is a Japanese language film.

This issue has occurred in the past with other Domesday captures but I used https://github.com/atsampson/ttconv until it stopped working now, and I can't sort out what changes they made before merging the updates to 1.0.7.

```
Unsupported SCC word: 0x7c                                                  
Unsupported SCC word: 0x7c                                                  
Unsupported SCC word: 0x107c                                                
Reading: |███████-------------------------------------------|  15% CompleteTraceback (most recent call last):
  File "/home/pip/.local/venv/ttconv/bin/tt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pip/.local/venv/ttconv/lib/python3.11/site-packages/ttconv/tt.py", line 439, in main
    args.func(args)
  File "/home/pip/.local/venv/ttconv/lib/python3.11/site-packages/ttconv/tt.py", line 320, in convert
    model = scc_reader.to_model(file_as_str, reader_config, progress_callback_read)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pip/.local/venv/ttconv/lib/python3.11/site-packages/ttconv/scc/reader.py", line 621, in to_model
    context.process_line(scc_line)
  File "/home/pip/.local/venv/ttconv/lib/python3.11/site-packages/ttconv/scc/reader.py", line 556, in process_line
    self.process_text(word, line.time_code)
  File "/home/pip/.local/venv/ttconv/lib/python3.11/site-packages/ttconv/scc/reader.py", line 460, in process_text
    self.buffered_caption.append_text(word)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append_text'
```

I wonder if possibly the capture has errors or is flawed and this is causing the "unsupported characters", or if it's just because Japanese character set is not supported?

thank you

**Comment by palemieux** [comment]
@valnoel Can you look at this issue in the context of your work improving the SCC reader?

**Comment by valnoel** [comment]
The SCC reader does not currently support Japanese characters, which do not appear in the CEA-608 specification.

It seems an [extension](https://en.wikipedia.org/wiki/EIA-608#Non-Western_Norpak_Character_Sets) was once submitted to the specification, but I don't have any more information about it...

Otherwise, it seems CEA-708 introduces the Unicode characters support, which allow the display of Japanese and other languages.

@palemieux What do you think?

**Comment by palemieux** [comment]
> Otherwise, it seems CEA-708 introduces the Unicode characters support, which allow the display of Japanese and other languages.

Ok will look at this next week.

**Comment by palemieux** [comment]
@rktcc Can you provide a link to the forum discussion thread? I could not find any specification for carrying arbitrary unicode characters in SCC.

**Comment by palemieux** [comment]
I have joined the discord server.

In the meantime, I have spent some quality time staring at the sample file and it does not look like CEA 608 at all, e.g.:

![image](https://github.com/sandflow/ttconv/assets/4871350/18002d4c-2385-4957-aa51-423dc119a3d8)

Is that noise/errors from the laserdisc capture? Could it be something totally different like bitmaps?
